[package]
name = "micro-grammars"
version = "0.1.0"
authors = ["Felix S. Klock II <pnkfelix@pnkfx.org>"]

build = "build.rs"

[build_dependencies.pgy]
path = "../../../pgy"

[dependencies.pgy_runtime]
path = "../../../pgy_runtime"
